<script src="{{ asset('admin_assets/js/lib/jquery-3.7.1.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/apexcharts.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/dataTables.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/iconify-icon.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/jquery-ui.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/jquery-jvectormap-2.0.5.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/jquery-jvectormap-world-mill-en.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/magnifc-popup.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/slick.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/prism.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/file-upload.js') }}"></script>
<script src="{{ asset('admin_assets/js/lib/audioplayer.js') }}"></script>
<script src="{{ asset('admin_assets/js/app.js') }}"></script>
<script src="{{ asset('admin_assets/js/homeOneChart.js') }}"></script>
<script src="{{asset('admin_assets/js/editor.highlighted.min.js') }}"></script>
<script src="{{asset('admin_assets/js/editor.quill.js') }}"></script>
<script src="{{asset('admin_assets/js/editor.katex.min.js') }}"></script>
<script src="{{asset('admin_assets/js/full-calendar.js') }}"></script>
<script src="{{asset('admin_assets/js/flatpickr.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

